# nixpacks.toml 
 
[variables] 
# Mantém o comportamento atual do build 
NODE_ENV = "production" 
NPM_CONFIG_PRODUCTION = "false" 
NIXPACKS_SPA_OUTPUT_DIR = "dist"
PORT = "4173"
# Supabase Configuration
VITE_SUPABASE_URL = "https://hjjzecodtfnerkxslzpd.supabase.co"
VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhqanplY29kdGZuZXJreHNsenBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4NDM4MzQsImV4cCI6MjA3NzQxOTgzNH0.sZ9NG-06i-5YTM3nNrYiQ5LDx9yQBh0YBb0WicGmams" 

# Se quiser controlar a versão do Node aqui: 
# (altere para nodejs_20 se seu projeto exigir Node 20) 
# Dica: mantenha alinhado com seu lockfile. 
[phases.setup] 
nixPkgs = ["nodejs_22", "bun"] 
# Pacotes úteis durante o build (opcional) 
aptPkgs = ["curl", "wget"] 

[phases.caddy] 
dependsOn = ["setup"] 
nixPkgs = ["caddy"] 
# Formata o Caddyfile que vamos incluir em /assets 
cmds = [ 
  "caddy fmt --overwrite /assets/Caddyfile" 
] 

[phases.install] 
dependsOn = ["setup"] 
# Use npm ci para reprodutibilidade (mantém seu fluxo atual) 
cmds = ["npm ci"] 
# cache de bun é opcional aqui; npm já é rápido com layer cache 

[phases.build] 
dependsOn = ["install"] 
# Build com Vite (mantendo bun, como no seu log) 
cmds = ["bun run build"] 

[start] 
# Servir a pasta dist com Caddy (SPA-friendly) 
cmd = "exec caddy run --config /assets/Caddyfile --adapter caddyfile 2>&1"