# Nixpacks Configuration for Production Build
[variables]
NODE_ENV = "production"
PORT = "4173"

[phases.setup]
nixPkgs = ["nodejs_20", "curl"]

[phases.install]
cmds = ["npm ci --include=dev"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run preview"