# nixpacks.toml - Configuração simplificada

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"
PORT = "4173"

[phases.setup]
nixPkgs = ["nodejs_22", "python3"]

[phases.install]
dependsOn = ["setup"]
cmds = ["npm ci"]

[phases.build]
dependsOn = ["install"]
cmds = ["npm run build"]

[start]
# Usar Python HTTP server para servir arquivos estáticos
cmd = "cd /app/dist && python3 -m http.server 4173 --bind 0.0.0.0"